### PR TITLE
New Article Section #174

### PR DESCRIPTION
**Pull request by edhenderson**
- add supplied articles hero image
- change layout for articles page to new template `blog.html` and wire up
- change layout for post pages to new template `blog-post.html` and wire up
- upgrade theme to version `1.2.0`
- new includes, `posts-featured`, `posts-regular` and `posts-all` to help with rendering of post previews on various pages
- new includes, `post-featured` and `post-regular` to render post previews
- additional metadata added to posts, `isFeatured` and author information

### CODE REVIEW

**Comment by davidgatti** [comment]
# Round bottom

Screen Shot 2020-11-01 at 2 59 39 PM

# Lighten up the header

Screen Shot 2020-11-01 at 3 00 47 PM

# Just one featured

Screen Shot 2020-11-01 at 3 01 35 PM

# No avatars in general

Screen Shot 2020-11-01 at 3 02 03 PM

# Wrong text

Screen Shot 2020-11-01 at 3 02 34 PM

# No high res image

Screen Shot 2020-11-01 at 3 03 05 PM

# Working sherable URLs

Screen Shot 2020-11-01 at 3 04 04 PM

# Contact form module

Screen Shot 2020-11-01 at 3 05 06 PM

# Text is displayed twice

Screen Shot 2020-11-01 at 3 06 46 PM

# Center article images

Screen Shot 2020-11-01 at 3 07 52 PM

**Comment by edhenderson** [comment]
This is good for another look. Thanks.

**Comment by davidgatti** [comment]
1. the bend under the headers is now gone from everywhere, and I want it back :)
2. Missing drop downs.

Screen Shot 2020-11-01 at 7 13 29 PM

**Comment by edhenderson** [comment]
Aha you want the curve for the articles, understood.

I just included your contact form, I'll investigate.

Thanks

**Comment by edhenderson** [comment]
@davidgatti The upgrade of the theme has caused the bottom footer curve to stop working AND the custom dropdown to stop rendering. I'll have to dig in.

**Comment by edhenderson** [comment]
@davidgatti Good for another look, issues resolved.

**Comment by davidgatti** [comment]
Regarding the curve we did not understand each other, I hope the following images will clarify the situation:

Screen Shot 2020-11-02 at 11 23 43 AM
Screen Shot 2020-11-02 at 11 23 47 AM
Screen Shot 2020-11-02 at 11 23 51 AM
Screen Shot 2020-11-02 at 11 24 01 AM

**Comment by edhenderson** [comment]
Aha, you said over the weekend "This bend is not present in other pages" - I took this as turn it off on other pages to be consistent with the new template. You meant the opposite. Let me resolve.

**Comment by edhenderson** [comment]
@davidgatti Good for a look Sir.

**Pull request merged**
