### PR TITLE
Custom CSS for contact form in article #201

### LINKED ISSUE #201: Custom CSS for contact form in article
This page shows at the end a different view of the contact page: https://landkit.goodthemes.co/career-single.html - could we do it the same, and only show this version in the article section? Or this would be to complicated to to with Jekyll?

Screen Shot 2020-11-07 at 12 20 07 PM

### PR DESCRIPTION
**Pull request by edhenderson**
- bottom of article now has contact form in the style of the template https://landkit.goodthemes.co/career-single.html
- closes #201

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
In the Landkit template this form view is more tight, the margins are not so massive, can we have the same margin/paddings/spacing to match the template one?

**Comment by edhenderson** [comment]
@edhenderson So what I had done here is pull in the contact_form include you already have. The spacing is as per the template, its just the contact form include that has lotsa breathing space. I'll need to cut that down (or pass in a spacing parameter) cause it still needs breathing space in the other places its used. See screengrabs for examples.

Screenshot 2020-11-10 at 09 32 07
Screenshot 2020-11-10 at 09 31 56

**Comment by davidgatti** [comment]
Feel free to modify all that is needed to make the contact page still look good, and also make the article version look good.

**Comment by edhenderson** [comment]
@davidgatti Good for another look.

**Pull request merged**
