### PR TITLE
The rectangles of the white papers #226

### LINKED ISSUE #226: The rectangles of the white papers
I need some extra details, a variable for:

- the name of the author of the feedback
- the URL to their site. 
- and display the logo at top of the company info

Screen Shot 2020-11-12 at 9 21 32 AM
Screen Shot 2020-11-12 at 9 22 08 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- style quote and add source (author)
- add client logo and url
- closes #226

### CODE REVIEW

**Comment by edhenderson** [comment]
Leaving this as a DRAFT for now as I know it will have a conflict with a couple of the other PRs.

**Comment by edhenderson** [comment]
@davidgatti Good for a look. You will need to add a wee bit of your own content (author names). Thanks.

**Comment by davidgatti** [comment]
@edhenderson can you resolve the conflict?

**Comment by edhenderson** [comment]
Oh. I didn't know about conflict, I am sorry. Will resolve this afternoon.

**Comment by edhenderson** [comment]
@davidgatti This is good for another look.

**Pull request merged**
