### PR TITLE
Remove empty space if possible #223

### LINKED ISSUE #223: Remove empty space if possible
I know you don't have 100% control over this things, but if possible it be nice if you could see if this empty space can be removed.

Screen Shot 2020-11-11 at 9 56 50 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- adjust height
- closes #223

### CODE REVIEW

**Comment by davidgatti** [comment]
Right, but now there is a scroll bar :) looks ugly. Any chance there is something you can do about it? No stress if you can't

Screen Shot 2020-11-13 at 9 23 39 AM

**Comment by edhenderson** [comment]
See my comments in the issue, it mentions the scrollbar.

**Comment by davidgatti** [comment]
In this case I will skip this PR.

**Comment by edhenderson** [comment]
Understood.

**Pull request closed without merging**
