### PR TITLE
Vs/#155 display the contact form at the end of  the article

### PR DESCRIPTION
**Pull request by vosaul**
The contact form in a separate component can be inserted anywhere. 
The parameter select = "list-of-items" - the list from the file "contact.yml" is passed to the contact form
#155

### CODE REVIEW

**Comment by davidgatti** [comment]
Screen Shot 2020-08-24 at 11 59 37 AM

The header can't be there just the form.

**Comment by vosaul** [comment]
On the contact page?

**Comment by davidgatti** [comment]
On the article page.

**Comment by vosaul** [comment]
I regrouped the inputs a bit because the fields of the industry list were wide and broke the markup and removed the banner from the contact form in articles
image

**Pull request merged**
