### PR TITLE
Fixed height for logos #263

### LINKED ISSUE #263: Fixed height for logos
I need the height to be locked, so if you have a SVG it won't grow out of proportion.

Screen Shot 2020-11-18 at 11 31 35 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- closes #263

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
I see the log as still taking up the whole width

Screen Shot 2020-11-26 at 11 25 14 AM

**Comment by edhenderson** [comment]
I thought this was a height based ticket? I shall reduce the `max-height`.

**Comment by davidgatti** [comment]
Better, but now the logo is centered, and it should not be. if you check the rest of the pages with logos.

Screen Shot 2020-11-27 at 10 03 04 AM

**Comment by edhenderson** [comment]
Aha, this is the only SVG logo, the others are all PNG. I pushed a fix for it now. 🏓

**Pull request merged**
