### PR TITLE
Remove one drop down from the contact page #264

### LINKED ISSUE #264: Remove one drop down from the contact page
For the industry I'd like to have a list of buttons, that you can click to select, to represent the drop down that there is now.

Screen Shot 2020-11-18 at 11 35 24 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- created new button-icon component
- replaced dropdown
- closes #264

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
- for the color I'd like to use `btn-secondary-soft`
- the buttons needs to be radio button and not check list so you can select only one industry
- if possible, center the buttons, I'd like to see how that looks.

**Comment by edhenderson** [comment]
@davidgatti Good for another look 🏓

**Comment by davidgatti** [comment]
All good @edhenderson see if you can resolve the conflict

**Comment by edhenderson** [comment]
@davidgatti Oh, that's strange, it was all rebased when I pushed it. Gimme 5 minutes.

**Pull request merged**
