### PR TITLE
New Input Fields - Issue: #92

### PR DESCRIPTION
**Pull request by tolgaouz**

### CODE REVIEW

**Comment by davidgatti** [comment]
@tolgaouz 126 files added? What is going on? and I see all .maps. I don't believe we need all fo that. we just need a drop down, for such simple thing I don't want to add 1GB of extra files.

**Comment by davidgatti** [comment]
I also see you changed completely the validation with Javascript validation, I want to use the build in HTML one. please remove this part.

**Comment by davidgatti** [comment]
And I see that all those file are for language translation, I don't need that. please remove them. The website is targeted ad US people, and there is only one language: English.

**Comment by tolgaouz** [comment]
Sure thing I removed map files and all but I didn't understand what you mean by validation, I haven't created any js functions for validation, I'm using HTML built-ins.

**Comment by davidgatti** [comment]
For whatever reason the tool tip were different when I was looking at it. strange, but now it is OK.

**Comment by davidgatti** [comment]
@tolgaouz check my changes to see how I did what I did, and learn from it.

**Pull request merged**
