### PR TITLE
Move the Featured bubble #179

### PR DESCRIPTION
**Pull request by edhenderson**
- remove FEATURED badge

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
@edhenderson please don't do stuff like this in the future. Please have a basic understanding of margins and how something should fit visually with the rest. 

Screen Shot 2020-11-05 at 12 35 23 PM

**Comment by edhenderson** [comment]
Thanks for the feedback. My apologies, I moved it to the equivalent place on the left hand side to show you what it looked like. I was aware the margins were a bit funky.

**Comment by edhenderson** [comment]
> You know what, I decided to remove that featured thing all together.

Do you mean the wee badge or the whole concept of Featured Articles? Let me know and I can amend. Thanks.

**Comment by davidgatti** [comment]
Remove the just the bubble.

**Comment by edhenderson** [comment]
Thank you.

**Pull request merged**
