### PR TITLE
White paper page for clients #202

### LINKED ISSUE #202: White paper page for clients
As the last thing, I want to add a new sub page where I will have a white paper describing what I did for each client. Right now on the home page there is a carrousel of clients. I want to replace the URL to the client page, with `read white paper` and when you click on it this view is going to be used: https://landkit.goodthemes.co/career-single.html

Screen Shot 2020-11-07 at 12 22 52 PM

### PR DESCRIPTION
**Pull request by edhenderson**
- added new fields for companies (subtitle, slug, info and opinion)
- wire up home page to link through to `/clients/xxxx` page
- new `client` layout
- 8 x new clients pages
- contact form added to bottom of client page
- closes #202

### CODE REVIEW

**Comment by davidgatti** [comment]
Look good, will play with this in the upcoming days

**Comment by davidgatti** [comment]
@edhenderson How can I edit the boxes on the side?

**Comment by edhenderson** [comment]
Check `categories.yaml`, it has the data.

**Comment by davidgatti** [comment]
Screen Shot 2020-11-10 at 1 51 52 PM

I will, in the mean time I need to be able to edit this per client.

**Comment by edhenderson** [comment]
Understood. Let me wire that up to something. Standby.

**Comment by edhenderson** [comment]
There is now a `subtitle` field in `companies.yaml` for you to use. We can rename if if needed.

**Comment by davidgatti** [comment]
This is bit unlogical, it be nicer if you could add this to the header of each client page, this way you open one file and have all the info of that particular page in one place.

**Comment by edhenderson** [comment]
@davidgatti Yes, I agree, it becomes weird sometimes with Jekyll and trying to separate the data from presentation etc. can become opinionated.

I don't want to have to put something like:

```
          <!-- Heading -->
          <h1 class="display-4 mb-2">
            {{ company.company_name }}
          </h1>

          <!-- Text -->
          <p class="font-size-lg text-gray-700 mb-5 mb-md-0">
            {{ company.subtitle }}
          </p>
```

into the markdown files.

**Comment by edhenderson** [comment]
What I can do is move that `subtitle` into the company file, e.g.

```
---
layout: client
slug: atkins
subtitle: TODO
---

<p>Atkins relied heavily on video editing software and recognized that its process was hemorrhaging costs. Atkins was using different Windows machines with video editing software and was then having to upload huge data sets to its website. David came up with the solution to simplify costs by creating a server running on AWS with a Windows operating system, graphic art, and Nvidia Cuda so that Atkins would have a video editing rig in the cloud. The cloud video editing rig was more powerful and much faster than the desktop environment.</p>

<p>that’s not all, because David made video editing in the cloud possible because of a Samba server and an open VPN server, which are 2 of his products. The Samba server allowed Atkins to have access to video files from a local computer just by mounting the drive locally, and then by doing the same thing on the Windows server. Access to files was more straightforward, faster, and simpler. With Atkins now using a Samba server, it meant that the same drive could be shared in multiple places to allow uploading with little effort and to easily edit videos in the cloud. The open VPN server that David implemented meant that the video editing rig in the cloud was hidden on a private network and a private subnet so that there was no risk and no malicious actors could gain access to the machine, because there was no public access to the rig.</p>

<p>David also went above and beyond to save Atkins additional time and costs. David implemented a lambda function that would monitor the instance and turn the server off after a few hours when not in use and the CPU usage was low. This preserved costs by preventing the video editing server from constantly running. David also created a desktop app that would allow Atkins employees to turn off the instance when it wasn't needed, which prevented them from having to go through the AWS console. David also included clear and concise documentation to easily understand the app's function and how to use it.</p>
```

**Comment by edhenderson** [comment]
Good for another look, fixed and squashed.

**Comment by edhenderson** [comment]
Good for another look! @davidgatti

**Pull request merged**
