### PR TITLE
Center the text #287

### LINKED ISSUE #287: Center the text
The text under the logo needs to be centered.

Screen Shot 2021-03-06 at 11 27 47 AM

### PR DESCRIPTION
**Pull request by edhenderson**
- closes #287

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
LOL :D I think your monitor is tilted to the right to much, the text did slide a bit to much ;) please check the result of your changes.

Screen Shot 2021-03-08 at 8 23 27 AM

**Comment by edhenderson** [comment]
@davidgatti My apologies, I had left a commit on my local box. It didn't push up. Should be good now.

**Comment by davidgatti** [comment]
@edhenderson after looking at the change I realized what was off with that part of the page, the margin where wrong. I did check the original template https://landkit.goodthemes.co/desktop-app.html, and market the difference. 

- put back the text to the left
- adjust the margins between the text and the icons to match the original template.

Screen Shot 2021-03-08 at 8 15 44 PM

**Comment by edhenderson** [comment]
🏓

**Pull request merged**
