### PR TITLE
Vs/#153 fine tune the contact page

### PR DESCRIPTION
**Pull request by vosaul**
I changed contact.yaml - added industries list. 
The contact form is made in a separate component with the ability to select a list of states or a list of industries, this is passed by the parameter, so if in the future you want to add for example a selection of software or something else - just add the appropriate list in contact.yaml, insert contact_form. HTML and pass list name.
#153

### CODE REVIEW

**Comment by davidgatti** [comment]
- the height between the body and the rest was not changed
- the AWS Services drop down gose over the footer as seen bellow

Screen Shot 2020-08-24 at 11 56 13 AM

**Comment by vosaul** [comment]
I'm sorry, I didn't notice, I'll fix it

**Comment by vosaul** [comment]
fixed in #155

**Comment by davidgatti** [comment]
@vosaul please check the conflicts.

**Pull request closed without merging**
