### PR TITLE
Article image reorganization #217

### LINKED ISSUE #217: Image resolutions
The images that I have for the articles have a resolution that was designed for the old template. Now since we are using the new one, all the resolutions and proportions are bit off, based on the template, could you write all the 3 resolutions that would be ideal for the layout that we have now?

- Mini image for the article card
- Medium image for the featured article
- The big one for the header, for example now with the non white background it is obvious the resolution is not right.

### PR DESCRIPTION
**Pull request by davidgatti**
I did reorgaznie the article images to:

- Match the right resolution
- Have the right quality
- And rename the file names to me easier to understand what are they for

All images are also 16:9 in proportion.

- closes #217

### CODE REVIEW

**Comment by davidgatti** [comment]
@edhenderson I need some adjustments how the images are being displayed in the featured section, as you can see from bellow, the images are cut by the page. I did set the proportion to be 16:9 to make the life of a designer easier. So we have to adapt the page to the new proportion.

Screen Shot 2020-11-14 at 10 27 58 AM
Screen Shot 2020-11-14 at 10 26 27 AM

**Comment by edhenderson** [comment]
So if we change the CSS to allow the entire image to be visible then we will have some white borders in some places. Is that OK?

**Comment by davidgatti** [comment]
It be best if you could share a screenshto.

**Comment by edhenderson** [comment]
screencapture-localhost-4000-articles-2020-11-14-18_00_15

**Comment by edhenderson** [comment]
screencapture-localhost-4000-articles-how-to-how-to-hire-the-technical-team-html-2020-11-14-18_01_11

**Comment by edhenderson** [comment]
@davidgatti Couple screengrabs from your branch AFTER I did a commit to resolve them all.

**Comment by davidgatti** [comment]
@edhenderson the featured section looks perfect, but I did not want you to make any changes to the individual article cards, those are OK as they are

+ 

Did you also make changes to make sure the OG tags link to the right image? If not I think it be best to link to the featured version of the image.

**Comment by edhenderson** [comment]
Featured: great, glad to hear.
Individual article cards: I made no changes here, just using the right filenames.

I made no changes to OG tags.

**Comment by davidgatti** [comment]
> I made no changes to OG tags.

In that case i think that is not good :) if the file name changed should you also update the header to point to the right image for the OG?

**Comment by edhenderson** [comment]
Sorry, I wasn't aware we needed to update the `og:image` tags as part of this. I will do so shortly on this branch (and fix that conflict).

**Comment by edhenderson** [comment]
I'll need to take a look as some pages use `image:` and some use `featured:` - standby.

**Comment by edhenderson** [comment]
@davidgatti Good for another look.

**Comment by edhenderson** [comment]
Thank you!

**Pull request merged**
