### PR TITLE
Meeting Page - Issue: #89

### PR DESCRIPTION
**Pull request by tolgaouz**

### CODE REVIEW

**Comment by tolgaouz** [comment]
Ah!! Okay lol

**Comment by davidgatti** [comment]
One more time, maybe this time you can do it ;) this is the meeting page, with the header 

Screen Shot 2020-05-15 at 10 17 19 AM

and this what you did:

Screen Shot 2020-05-15 at 10 17 21 AM

See if you can spot the difference.

**Comment by tolgaouz** [comment]
Ah!! I didn't know you'd want a cover image like that in the meeting page. Adding now

**Comment by tolgaouz** [comment]
Added the header image now

**Pull request merged**
