### PR TITLE
Update post.html #33

### PR DESCRIPTION
**Pull request by tolgaouz**

### CODE REVIEW

**Comment by davidgatti** [comment]
Question, did you do this as a quick fix, or did you check the template ti find out how it is done on the other pages?

**Comment by tolgaouz** [comment]
No, it was a quick fix actually

**Comment by tolgaouz** [comment]
Should I change 404.html as well with a sticky footer ?

**Comment by davidgatti** [comment]
OK, lets not do a quick fix, please make the right fix so the HTML is consistent.

**Pull request closed without merging**
