### PR TITLE
Add new article

### PR DESCRIPTION
**Pull request by davidgatti**
@edhenderson I added a new article but when I build the project locally I get this error, as you can see from this commit, everything is in the right place. So why the error keep saying that the images are not where they should be?

```
Configuration file: /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/_config.yaml
            Source: /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting
       Destination: /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Disabled in site.config.
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Could not locate the included file '/assets/img/articles/how-to-lower-aws-costs/cover.jpg.base64' in any of ["/Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/_layouts/article.html
bundler: failed to load command: jekyll (/Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/bin/jekyll)
IOError: Could not locate the included file '/assets/img/articles/how-to-lower-aws-costs/cover.jpg.base64' in any of ["/Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/tags/include.rb:223:in `locate_include_file'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/tags/include.rb:205:in `render'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:127:in `render_liquid'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:190:in `render_layout'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:159:in `place_in_layouts'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:89:in `render_document'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:63:in `run'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:532:in `render_regenerated'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:517:in `block (2 levels) in render_docs'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:516:in `each'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:516:in `block in render_docs'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:515:in `each_value'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:515:in `render_docs'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:207:in `render'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:80:in `process'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `load'
  /Users/davidgatti/Documents/GitHub/0x4447/0x4447_webpage_consulting/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `<top (required)>'
```

### CODE REVIEW

**Comment by edhenderson** [comment]
I'll take a look this afternoon.

**Comment by edhenderson** [comment]
I checked master and that build ok. I'll check your branch.

**Comment by edhenderson** [comment]
This is because jekyll is looking for the file `/assets/img/articles/how-to-lower-aws-costs/cover.jpg.base64` as you asked me to make all the cover images into base64 versions. So the fix is either, I tweak the code to allow non-base-64 versions OR you make a base64 version of this file. Let me know.

**Comment by davidgatti** [comment]
Hmm but all the images for the article that we have right now are not base64, so how they work, and this new ones don't? Ps I thought that the solution will work, in a automatic way, meaning at build time you will convert the header image in to base64 and embed it in to the HTML itself.

If this is not the case, can you explain step by step how what you done works.

**Comment by edhenderson** [comment]
I would need to find the issue for what exactly happened but

- you asked for them to be base64, maybe part of the Jekyll build process
- I said this wasn't something Jekyll could do, would need to be another tool that did it
- I converted all cover images to base64 and wired up Jekyll to use them

To resolve this I can tweak the code to allow non-base64 images too?

**Comment by edhenderson** [comment]
See my PR above which will help resolve this problem.

**Pull request merged**
