### PR TITLE
Vs/#139 new title structure

### PR DESCRIPTION
**Pull request by vosaul**
Changed head as required
in homepage and articles page added field type in the front-matter
#139

### CODE REVIEW

**Comment by davidgatti** [comment]
The Issue was not super clear

- For this page: http://localhost:4000/articles/, the title should be `AWS Cloud Consulting - Our Articles - 0x4447`
- for the article page itself, this part `AWS Cloud Consulting` should not be present

**Comment by vosaul** [comment]
changed as required

**Comment by davidgatti** [comment]
1. Why did you commented out Google Analytics?
2. The titles are still not right, could you focus, this is some super crazy basic stuff that is taking way to long to do, I will write done one more time what needs to be done. And after this I'm done.

http://localhost:4000/ -> `AWS Cloud Consulting - 0x4447`
http://localhost:4000/schedule/ -> `AWS Cloud Consulting - Schedule A Meeting - 0x4447`
http://localhost:4000/contact/ -> `AWS Cloud Consulting - Contact Us - 0x4447`
http://localhost:4000/articles/ -> `AWS Cloud Consulting - Our Articles - 0x4447 `
http://localhost:4000/articles/knowledge/ -> `AWS Cloud Consulting - Knowledge - 0x4447` <- of course the same analogy for all the tags this is just an example! I'm not going to do all the possibilities 
http://localhost:4000/articles/knowledge/cloudformation-tips-and-tricks.html -> `CloudFormation Tips and Tricks - 0x4447` <- of course the same analogy for all the articles this is just an example! I'm not going to do all the possibilities

**Comment by vosaul** [comment]
Sorry, the commented Google script should not get to committee, I commented on it for debugging that requests from localhost did not get to Google analytics.
Here is the title structure after the last edit:
| page | title |
|---|---|
| home page | AWS Cloud Consulting - 0x4447 |
| page | AWS Cloud Consulting - Schedule a free meeting - 0x4447 |
| page |AWS Cloud Consulting - Contact - 0x4447 |
| page |AWS Cloud Consulting - CloudFormation Tips and Tricks - 0x4447 |
| page |AWS Cloud Consulting - CloudFormation Tips and Tricks - 0x4447 |
| page | AWS Cloud Consulting - Articles - Knowledge - 0x4447
| article | CloudFormation Tips and Tricks - 0x4447 |
| article | The Importance of CloudFormation Files - 0x4447 |

**Comment by vosaul** [comment]
solved

**Comment by davidgatti** [comment]
If this table reflects your new work, then it is wrong.

**Comment by vosaul** [comment]
Did I misunderstand something again?
----
home = AWS Cloud Consulting - 0x4447
other pages = AWS Cloud Consulting - page.title - 0x4447
article = page.title - 0x4447

**Comment by davidgatti** [comment]
Other pages is the misunderstanding. There are no other, all links provided are to individual sites.

**Comment by vosaul** [comment]
I understand what's going on, I'll fix it now

**Comment by vosaul** [comment]
`<title>AWS Cloud Consulting - Articles - 0x4447</title>` 

`<title>AWS Cloud Consulting - How To - 0x4447</title>`

`<title>AWS Cloud Consulting - Knowledge - 0x4447</title>`

`<title>AWS Cloud Consulting - Contact Us - 0x4447</title>`

**Pull request merged**
